name: general_datetime
description: "general_datetime is an package to handle all calendars and dates. The powerful interface can make any custom calendars"
version: 1.2.1
homepage: https://github.com/ali-you
repository: https://github.com/ali-you/general-datetime-package
documentation: https://github.com/ali-you/general-datetime-package
issue_tracker: https://github.com/ali-you/general-datetime-package/issues
topics:
  - date
  - time
  - calendar
  - utils
  - service

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0